### ISSUE TITLE
Relay Wled & Sound 

### ISSUE THREAD

**Issue by tourer4778** [atuline/WLED#103]
Hello, I use WLed with sound. With Wled without sound you can connect a relay to D6. But that doesn't work with Wled with sound. Is there a way to switch a GPIO when Wled with sound is switched on?

**Comment by itsboo07** [comment]
Even I have the same issue... It's not working... Did you find a fix @tourer4778?

**Comment by softhack007** [comment]
Hello @tourer4778,

It should work the same way as in WLED without SR. You have to configure the  Relay Pin in Config -> LED preferences. The default value is -1, meaning no relay connected.

![20220715_223130](https://user-images.githubusercontent.com/91616163/179306628-8f361fa4-de6e-4298-b986-025ec56ec232.jpg)

Please try. If that works for you, please close this issue.
