### ISSUE TITLE
dev version  LED Preferences Can't save

### ISSUE THREAD

**Issue by zx804262156** [atuline/WLED#104]
dev version  LED Preferences Can't save
Save button not working

**Comment by ewoudwijma** [comment]
Working on it! Workaround for now: check multiple panels, add 1 horizontal and 1 vertical. Then save should worm

**Comment by zx804262156** [comment]
@ewoudwijma 
I find
Button pin
IR pin
Unable to save successfully, pin is -1

**Comment by atuline** [comment]
> I find
> Button pin
> IR pin
> Unable to save successfully, pin is -1

The SR version of WLED disables IR. To enable IR, you will need to go into wled.h and 'un' disable it and then compile. Either way, we do not support IR functionality.

**Comment by zx804262156** [comment]
> > 我发现
> > Button pin 
> > IR pin
> > 无法成功保存，pin 为 -1
> 
> WLED 的 SR 版本禁用 IR。要启用 IR，您需要进入 wled.h，'un' 禁用它，然后编译。无论哪种方式，我们都不支持 IR 功能。
> 
> 我们还必须确定出现此问题的设备的确切状态，并记录重现问题所需的确切步骤。这不是“保存按钮不起作用”的断断续续的情况，因为它在我们的大部分测试中都在工作。

thank you for your help，To enable IR，will need to go into wled.h,Where to modify，then compile ？I did not understand。

**Comment by atuline** [comment]
> 
> 
> > > 我发现
> > > Button pin
> > > IR pin
> > > 无法成功保存，pin 为 -1
> > 
> > 
> > WLED 的 SR 版本禁用 IR。要启用 IR，您需要进入 wled.h，'un' 禁用它，然后编译。无论哪种方式，我们都不支持 IR 功能。
> > 我们还必须确定出现此问题的设备的确切状态，并记录重现问题所需的确切步骤。这不是“保存按钮不起作用”的断断续续的情况，因为它在我们的大部分测试中都在工作。
> 
> thank you for your help，To enable IR，will need to go into wled.h,Where to modify，then compile ？I did not understand。

Summary: We do not support IR and have disabled it. You would need to modify the source code to do so.

**Comment by ewoudwijma** [comment]
Solved in latest commit
