### ISSUE TITLE
What name is default_envs use appropriate for esp-12 nodemcu v3 8266

### ISSUE THREAD

**Issue by tctmaster** [atuline/WLED#105]
i use esp-12e nodemcu v3 8266 so please declare which line is suitable because in .ini only default_envs = soundReactive_esp32dev and eth,
Can I ask more if I use mic max9814, which pin of ESP-32 should I plug in because I have ordered and waiting for delivery, now I only use esp-12 temporarily for testing first?
thanks any bro help me

**Comment by omski** [comment]
The support for ESP8266 has been deprecated. I hardly suggest to use an ESP32!
How to hookup analog and digital mics is described in the docs. https://github.com/atuline/WLED/wiki
I would hardly suggest to use a digital microphone!

**Comment by tctmaster** [comment]
> The support for ESP8266 has been deprecated. I hardly suggest to use an ESP32!
> How to hookup analog and digital mics is described in the docs. https://github.com/atuline/WLED/wiki
> I would hardly suggest to use a digital microphone!

I'm using ESP32 already and it's solved but I want to ask when will the source code of WLED_Sound 0.12.0 final be available?

**Comment by omski** [comment]
https://github.com/atuline/WLED/tree/v0.12.0
Is this what you are looking for?

**Comment by atuline** [comment]
We're also waiting for AirCoookie to finish 0.13.0 before making an official release. If the past is anything to go by, we may need to update that as well, as the community finds issues with the official release.
