### ISSUE TITLE
A suggestion for the documentation

### ISSUE THREAD

**Issue by bphermansson** [atuline/WLED#110]
Hi! 

I have a suggestion for the documentation. In the chapter about First Steps, a text about how to connect to the device could be added:

##  First Steps
_After uploading WLED to the Esp, use your phone and connect to the WLED-AP using the password 'wled1234'.
Click 'Login to network' when the notification about this shows up. You are then transfered to the WLED's start page, and here we should click "WIFI SETTINGS" to connect to the local network. Fill in the settings for your local Wifi network, and then click 'Save & Connect'. The device will reboot and if everything worked it will now be connected to the local network. Finding it's IP-address can be done via the network routers administration page, or via an mobile app like Fing were you can find a new device called "wled-WLED". Open this IP in a webbrowser to access WLED's control page._ 
 
1. On the WiFi Setup page, it is highly re...

Regards Patrik

**Comment by ewoudwijma** [comment]
Good suggestion: added to the page!
