### ISSUE TITLE
I have somehow managed to install "WLED version 0.12.1-b1" and I can't seem to find it again

### ISSUE THREAD

**Issue by docmishra** [atuline/WLED#113]
Hi, 

Thank you for your excellent work on this project, it really is fantastic and much appreciated! 
I have a bit of a random question. I set my lights up (3 EPS 32's) some time ago and was just about to set some more up now. 

I can't figure out how but I seem to have WLED 0.12.1-b1 (build 2105112) currently installed on the ESP32's with the sound reactive functionality with the sound option in the menu. I can't however seem to find the binary for this anywhere now!? The releases page only has bin of "WLED 0.12.0 (build 2104030)" ?! I feel like I'm being really silly but just thought I'd ask what was going on!?

**Comment by atuline** [comment]
As I recall, the original 0.12.0 from AirCoookie had some issues, so one of the team members here updated our release with a later/better version of WLED.
