### ISSUE TITLE
VBAN

### ISSUE THREAD

**Issue by ProchyMicrochip** [atuline/WLED#114]
Hello,
First of all, I very appreciate your cool project, but I was wondering if will be posible to not use mic for soundreactive, but direct VBAN audio stream, there is one nice sketch that can easily convert VBAN stream to Int value.

**Comment by atuline** [comment]
Sounds interesting. We have had some issues with the reliability of WiFi when using WLED, High speed audio combined with the overhead of WLED could be an interesting test. Feel free to join us on Discord to discuss. Would be open to merging a PR on this after some discussion.
