### ISSUE TITLE
connection problem with esp8266 1mb

### ISSUE THREAD

**Issue by smoochiee** [atuline/WLED#122]
having issue on connectivity with esp8266 1mb flash size..can you compile a version for this esp8266

**Comment by softhack007** [comment]
See issue #159

README states that the ESP8266 branch is no longer receiving regular updates. Reasons explained in https://github.com/atuline/WLED/issues/159#issuecomment-1006640255 

Currently you need an ESP32 to run WLED-SR. Technicially the 8266 is not fast enough for our audio processing code.
