### ISSUE TITLE
Possible to increase USB (serial) baud rate?

### ISSUE THREAD

**Issue by sofakng** [atuline/WLED#123]
Is it possible to increase the USB (serial) baud rate in this fork of WLED?

I'd like to use it for HyperHDR (ie. Hyperion) but they recommend a baud rate of 2M for RGBW lights.

**Comment by netmindz** [comment]
USB port is normally just for debugging. Can you describe your setup further

**Comment by gulliver103** [comment]
It is now possible to increase the USB (serial) baud rate in the new wled-master release  b7

**Comment by softhack007** [comment]
Seems the question is answered. Closing.
