### ISSUE TITLE
Enable IR by default

### ISSUE THREAD

**Issue by mase76** [atuline/WLED#124]
Hi!
Can you enable IR by default to have it in the release builds?

**Comment by atuline** [comment]
We're mulling that one over. One challenge is that WLED appears to have limited IR functionality and no one on the team is currently prepared to add sound oriented functionality to the IR controls.

So, it may yet get enabled, but after that, you're most likely on your own.

**Comment by mase76** [comment]
But then I can use the default IR functions, that I have with the original WLED.
