### ISSUE TITLE
WiFi fails when sync enabled 

### ISSUE THREAD

**Issue by clayclai** [atuline/WLED#126]
**Describe the bug**
With binary soundReactive_WLED_0.12.0_ESP8266.bin flashed onto a NodeMCU ESP8266, I find that wifi becomes so unusable after "Enable instance list" and/or "Make this instance discoverable" are checked. "Enable instance list" alone won't do it. After I reflash a device, I can test whether "Make this instance discoverable." alone will cause the problem. After checking both "instance" boxes on the sync page, I have only been able to regain control by reflashing the device.

**To Reproduce**
This happens every time. To reproduce flash NodeMcu Mini Wireless D1 Module for ESP8266 ESP-12F or ACEIRMC ESP8266 D1 Mini WiFi Dev Board ESP-12 ESP-12F NodeMcu Mini Module WeMos Lua 4M (multiple samples from these 2 makes reproduced this problem without fail.) with your bninary soundReactive_WLED_0.12.0_ESP8266, and enable "Enable instance list" and "Make this instance discoverable."  Then reboot and try to connect.
**Expected behavior**
I expect enabling these two features will not take down wifi. This is how it works with  WLED_0.12.0_ESP32.bin & WLED_0.13.0-b2_ESP8266.bin on both the above 8266 devices and WLED_0.9.1_ESP32.bin, soundReactive_WLED_0.12.0a_ESP32.bin, and SR_esp32dev.bin on NodeMCU ESP32 devices

**WLED version**
 - Board: ACEIRMC ESP8266 D1 Mini WiFi Dev Board ESP-12 ESP-12F NodeMcu Mini Module WeMos Lua 4M Bytes
 - Version: soundReactive_WLED_0.12.0_ESP8266.bin
 - Format: Binary

**Additional context**
Everything else seems to work as expected. The above setup will even sync audio with a ESP32 transmit, even though you can't see the instance. I also did notice that they were unchecked by default in this release, which is a good otherwise I wouldn't even be able to access after a reflash.

Great Project BTW

I just checked on one device and it seems I can reproduced this problem by enabling "Make Discoverable" alone. Is it possible this is creating so much traffic (even with no other nodes on its network) that it can't communicate?

Thank you for your help!

**Comment by clayclai** [comment]
Greetings Andrew,

Thank you for your quick reply.

I don't think my problem is related to Aircoookie#1842. It's not clear 
if he is using the SR version or not. My problem only occurs with the SR 
8266 version. His problem was he couldn't see all his devices on the 
instance list because he had the ports wrong. My problem is that turning 
on  "Make Discoverable" has the effect like DDOS on that node, so it 
needs to be reflashed to regain control. Otherwise, if "Make 
Discoverable" is not enabled, the node appears to work as normal, 
syncing with the master, even for audio, and the node can still be 
accessed individually via IP, so that could be a workaround. In anycase, 
I have decided to abandon the 8266 for SR nodes. I was hoping to save a 
little money by using 8266 for nodes in a SR system, but considering 
that even resolving the above problem would (or using the workaround) 
still leave nodes that can't do FFT effects or be upgraded to 13.x and 
above, when for a few dollars more...

My application is a little different from other WLED applications I have 
so far read about—I am using it on bicycles. This requires 3 
nodes(controllers), electrically independent. One slave node (with 
battery & LEDs) for each wheel, and then a master node for the frame. 
The master node is on the frame. It has both a mic and a button. It runs 
in AP mode. The 2 wheels come up and attach to the master's AP and are 
synced to it. This works very well. I initially assumed that the master, 
with the AP, would need to boot first, so that the slave nodes could 
find it rather than launching their own APs. As it turns out, this isn't 
a problem. No matter what order they are powered up, everybody finds 
their place and no "excess" APs are launched. Sweet!

After I took my system apart the other day to experiment with the 8266 
instance list, and put it back together, it developed a new problem that 
has turned into a real head scratchier for me. So I hope you can offer 
some insight.
Previously, the push button on the master node shutdown,powered up or 
changed effects on all three nodes. Now it affects only the master node. 
The wheels don't respond. Now, here is where my usual troubleshooting 
techniques have run into a wall.
!) Clicking my Power Toggle and Effects presets on the master web UI 
activates all nodes as expected. So,  I know those presets sync to the 
wheel nodes, and are properly configured.

2) Pushing the button has the expected effect on the master node. So I 
know the button is doing its job of triggering the presets.

It's like 2 + 2 don't equal 4 anymore! The button on master of these 3 
SR nodes was working as expected (shutting down or starting, changing 
effects on all three nodes) for weeks now before something changed a few 
days ago. A set of 3 8266 non-SR nodes that I was using prior to SR 
still operates as expected..

So, what would cause a preset that syncs across all three nodes when 
clicked in the web UI, to only affect the node with the button when the 
button triggers the preset. Any insight into this problem would be 
greatly appreciated.

Best regards,

Clay



Clay Claiborne
Venice, CA 90291
(310) 581-1536

**Comment by clayclai** [comment]
Thank you for your time and suggestions. I will join the discard channel.

I may also try to capture the wifi packets to see what may be different
between a preset triggered via button vs. web ui. But know that your
version worked the same as AC's with regards to the push button and sync
out of the box. Did for weeks. I screwed something up, and when I figure it
out, I will learn something b/c now it seems a paradox. Button NOW triggers
preset only for its controller, web ui triggers preset across all synced
controllers.???

Clay

**Comment by atuline** [comment]
I've had to do a factory reset onmany an occasion as a result of firmware upgrades, because, of course, we add new features and modify EEPROM locations as well. So many config issues can be a real challenge to track down.
