### ISSUE TITLE
Got 10.1 working on esp 8266 but with rebooting issue when accessing web UI

### ISSUE THREAD

**Issue by makeroutlet** [atuline/WLED#127]
Working on 10.1 working on esp 8266 but with rebooting issue when accessing web UI, is this just bc the 8266 cant handle this repo? I ordered some esp32 but wondering if it was just me

**Comment by softhack007** [comment]
See issue #159 

README states that the ESP8266 branch is no longer receiving regular updates. Reasons explained in https://github.com/atuline/WLED/issues/159#issuecomment-1006640255 

Currently you need an ESP32 to run WLED-SR. Technicially the 8266 is not fast enough for our audio processing code, so it's not so easy to 'release th latest dev for esp8266'.
