### ISSUE TITLE
Failed updating firmware!  Please check your file and retry!

### ISSUE THREAD

**Issue by glowingkitty** [atuline/WLED#131]
I compiled the latest /dev version of your WLED fork and uploaded it to my ESP32 running your previous WLED fork (/dev) from a few days ago - by using the OTA update feature of WLED. But it always crashes... any idea why?

"Failed updating firmware!
Please check your file and retry!"

**Comment by atuline** [comment]
Afraid not. Feel free to join the Discord forums to discuss further. According to one of the developers, there WAS an issue a while back, but it should be OK now. That being said, that same developer just added an interpreter, which needs a LOT of work.

In the meantime, when updating, you should always perform a 'Security & Updates | Factory Reset'.

**Comment by ewoudwijma** [comment]
'One of the developers' might have an idea why this is ;-)
Recent versions have the following line in their platformio while older versions didn't have that: 
board_build.partitions = tools/WLED_ESP32_4MB_1MB_FS.csv
So can you try if it works if you comment that out?

**Comment by Angel-1024** [comment]
> 'One of the developers' might have an idea why this is ;-) Recent versions have the following line in their platformio while older versions didn't have that: board_build.partitions = tools/WLED_ESP32_4MB_1MB_FS.csv So can you try if it works if you comment that out?

commenting it will cause compiling error
"Error: The program size (1329890 bytes) is greater than maximum allowed (1310720 bytes)"

Compile with this option and flash firmware via cable, not by OTA, this way works.

**Comment by atuline** [comment]
When I compile, I now use env:soundReactive_esp32dev when compiling, again, not OTA.
