### ISSUE TITLE
Line In Wiring Example get it not working 

### ISSUE THREAD

**Issue by v0r73x** [atuline/WLED#137]
Hi @ ALL,

I tried to get the line-in working on ESP32 with SR WLED, but I failed. 
Is there a possibility to Help me with a TRRS Breakout to connect to ESP32 with resistors and condensators? 

I suggest that will be a good enhancement for the Wiki, since i like the way with T-Splitting audio cable. 

the TRRS has 2 rings but in the example wiring it was just with 1 "Ring" i guess? 

My wiring looks like this: it should run as prototype but I cant get it run. 

![IMG_0302](https://user-images.githubusercontent.com/48632087/141615632-32dae4d7-bf90-4253-beb5-2b0ce1e9e44d.jpeg)

If someone can help me with this, or someone get line-in working on WLED please share your knowledge and I will write a short How to for it. 
many thanks and again, awsome project, anyway  ;)

**Comment by atuline** [comment]
Join the Discord so you can talk to others who have implemented this. Also, did you try the test sketch as provided in the troubleshooting page of the Wiki?
