### ISSUE TITLE
esp8266 no longer supported ?

### ISSUE THREAD

**Issue by DarthWeber** [atuline/WLED#138]
Hi and thanks for the fork. I want to add the sound reactive feature to my wemos d1 mini - and i am unsure if i should replace my esp8266 with esp32 since there are no more binaries for the beta of 0.13. Is there any reason ?

**Comment by atuline** [comment]
Had too many issues with the ESP8266 (mainly AP mode was breaking), so we stopped almost all development of the ESP8266 version a while back, The ESP32 version has FFT support, 2D support and more.

**Comment by makeroutlet** [comment]
i got it to work but on 8266 but it crashes nearly every time, runs smooth on esp32
