### ISSUE TITLE
MQTT enabled or not on source code

### ISSUE THREAD

**Issue by Markus1970** [atuline/WLED#143]
Hi All,

Just a question on how I can enable MQTT within the latest beta source code for ESP32.
In the WLED.h file looks the section for enable and disbable features in view of MQTT like this
`#ifndef WLED_DISABLE_MQTT
  #define WLED_ENABLE_MQTT         // saves 12kb
#endif`
IS MQTT now enabled or not? If not, whats needs to be commented out to get MQTT enabled?

Many thanks
Markus

**Comment by atuline** [comment]
I recommend playing around with AirCoookie's original WLED if you haven't already done so. It's not an area that we've spent any time on, and I believe we did disable it a while back. You might also want to get onto the WLED Discord.
