### ISSUE TITLE
MQTT doesn't work with SoundReactive

### ISSUE THREAD

**Issue by pancho1** [atuline/WLED#144]
Hi there,
my actual hardware is a SP511e board. All is working fine with the b3 SW, instead MQTT.
So I did my own build (config see below), but same issue. MQTT Parameters will not be saved in GUI.
What can I do do get both active SoundReactive and MQTT?
Many thanks!

> [env:sp511e_sound]
> board = esp_wroom_02
> platform = ${common.platform_wled_default}
> platform_packages = ${common.platform_packages}
> board_build.ldscript = ${common.ldscript_2m512k}
> build_flags = ${common.build_flags_esp8266} -D LEDPIN=3 -D BTNPIN=2 -D IRPIN=5 -D IRPIN=3
> lib_deps = ${esp8266.lib_deps}

**Comment by atuline** [comment]
Hi, I recommend that you get onto the WLED Discord to discuss with the community as our development and support (for our sound reactive fork) is entirely for the web based interface. Other members of the community may be able to assist.
