### ISSUE TITLE
Analog Microphone not working in 0.13.0-b6 (worked in 0.13.0-b4)

### ISSUE THREAD

**Issue by zx804262156** [atuline/WLED#162]
SR-WLED beta version 0.13.0-b6 microphone does not work.
Microphone type: Generic I2S, Generic I2S With Mclk, Generic I2S PDM. I have tried all of these options to no avail.

The microphone I'm using is INMP441, which works fine for me in SR-WLED beta version 0.13.0-b3.

**WLED version**
 - Board: [default_envs = soundReactive_esp32dev]
 - Version [SR-WLED beta version 0.13.0-b6]
 - Format [ Binary and self-compiled]

Thank you for your help!

**Comment by atuline** [comment]
Join up on the Discord to discuss. Looks like you compiled with the proper environment. Not sure if you performed a factory reset.

For binary, see https://github.com/atuline/WLED/wiki/Installing-and-Compiling

**Comment by zx804262156** [comment]
I have performed a factory reset

**Comment by rrlevy** [comment]
I'm also having mic issue with 0.13.0-b6

I'm using an analog mic (MAX9814) connected to ESP32 VP Pin (GPIO36).

I can see the waveform arriving at the ESP32 pin with my oscilloscope, but setting up Sound Input Settings won't work.
Even with 0 Squelch and 255 Gain, at Gravmeter effect there is NO MOVEMENT in the LEDs.

**Comment by rrlevy** [comment]
I also just flashed it with 0.13.0-b4 and the mic works fine there

**Comment by jonandel** [comment]
AGreed - I built one yesterday 0.13.0.b4 ESP32, SVP pin - and it works fine.  The gain was a bit low at first (default in WLED was 10?)

**Comment by atuline** [comment]
> I'm also having mic issue with 0.13.0-b6
> 
> I'm using an analog mic (MAX9814) connected to ESP32 VP Pin (GPIO36).
> 

How exactly did you flash it?

**Comment by rrlevy** [comment]
I downloaded the binaries from the Releases page.

I tried first flashing with ESPHOME and also later tried with ESPTOOL command line. Also flashed the v4 bootloader.

I also tried flashing the beta4 and later upgrading OTA with beta6, and the mic stops working after the update.

**Comment by rrlevy** [comment]
Here is the serial plotter of the same board:

![image](https://user-images.githubusercontent.com/14061585/149678335-d40bf218-58b8-4422-9446-5d59ea387cf1.png)

The mic is working on the board. There seems to be something with the code.

**Comment by rrlevy** [comment]
@atuline 
I don't know what happened but just after doing further tests, the mic simply started working on beta6....

I had tested everything before and I'm not sure what was the reason for the change. I had just reflashed the binary after running the serial plotter.

Just to make sure it really worked, I erased the flash memory, reflashed bootloader (v4) and beta6 binary, and it all worked again.

Sorry about that.

**Comment by FHeilmann** [comment]
One thing that's particular with the updated microphone code is that any change to the configuration requires a hard reset (via reset button) or powercycle. The reason for this is that a software reset (pressing reboot in the UI) doesn't properly reset the I2S peripheral of the ESP32 and leaves it in a disfunctional state. This is unfortunately a quirk of the underlying framework and something we cannot fix, if you have any suggestions how to clarify this, I'll be happy to hear them.

Bests,

Florian (Haribro)

**Comment by dosipod** [comment]
Hi guys , I just moved two ESP32 that are working fine with music reactive features   via line-in  from  sr 0.13.0-b4 to  sr 0.13.0-b6 and no more leds reaction . I moved back to  0.13.0-b4 and the issue is fixed . I have not changed anything after each update

**Comment by atuline** [comment]
When you flashed, did you:

https://github.com/atuline/WLED/wiki/Installing-and-Compiling#flashing-esp32-binaries

**Comment by dosipod** [comment]
I only flashed the binary with OTA , as it worked on its own the 3rd time  I assumed it was just as you said a matter of time  from when flashing is finished , I will redo the same with esptool because the guys reported issues with ESPHome Flasher . Is that what you want me to do ? I also have 3 other wled setups that I can test beside the two I a have already done testing

**Comment by rrlevy** [comment]
> I only flashed the binary with OTA , as it worked on its own the 3rd time I assumed it was just as someone said a matter of time from when flashing is finished , I will redo the same with esptool because the guys reported issues with ESPHome Flasher . Is that what you want me to do ? I also have 3 other wled setups that I can test beside the two I a have already done testing

@dosipod I had the exact same issue. Had to reflash by erasing, flashing bootloader and flashing binary and it finally worked.

**Comment by dosipod** [comment]
I think it is easier then I expected , just pressed reset after the OTA update worked ( reset by pressing the EN with no power recycle  , I think that should be mentioned to the guys as a first step to avoid complication

**Comment by victorcampeanu** [comment]
0.13.0-b4 works,  0.13.0-b6 works after OTA update then doesn't after a power off. restoring to  0.13.0-b4 works again

**Comment by atuline** [comment]
Please see the 'Its not working page', and the "Installing and Compiling" page.

**Comment by victorcampeanu** [comment]
it starts to work after a long press on reset but that is untill the next power off, you have to long press EN again.
also there is alot of noise, with room quiet it lights up randomly. 
restoring 0.13.0-b4 fixes all isuues

**Comment by btittelbach** [comment]
don't have a lot to contribute but also observed that upgrading to 13.1 on esp32 cololight-pro analog microphone stopped working where previously it worked fine. Downgrading to 12.0 makes microphone work again.

**Comment by smith844** [comment]
I concur, the microphone stops working under 0.13.0-b6 but works as advertised with b4.  I also have generic analogue set with MAX4466.  I have reverted to b4 and it works fine.  looking forward to the undoubted fix. 
Thanks to all for the fine work.

**Comment by softhack007** [comment]
We recently found out that analog microphone input sometimes does not work when you also have "analog buttons" (aka potentiometer) configured.
I2S uses the ADC1 unit; when there is another ADC1 operation by analogRead() then two drivers seem to be in conflict, as both want to use ADC1 but with different settings -> as result, I2S delivers silence.

Do you have "analog buttons" configured in your LED preferences? If yes - please check if the microphone works after changing all buttons to "disabled" and reboot via reset button.
