### ISSUE TITLE
IR Remote

### ISSUE THREAD

**Issue by UserWally** [atuline/WLED#165]
I can get an IR remote working perfectly on the non sound WLED version.
If I use the exact same settings using the sound reactive version it will not work. The receiver flashes but WLED is not processing anything.
I am using v.0.13.0-b6"Toki"
Any clues why the same setup works on one and not the other.

**Comment by atuline** [comment]
IR has been disabled by default (and we don't support it). You would need to go in and enable it and compile from source.
