### ISSUE TITLE
Alexa Discovery

### ISSUE THREAD

**Issue by tomste** [atuline/WLED#171]
Hi,

on my esp32 Alexa discovery is not working. With WLED original and an esp8266 it worked fine. Can someone help?

Regards,
Thomas

**Comment by mrstackit** [comment]
Hi,

i have the same issue with ESP32 i use a LedBoxV2. With 12.0 an 13.0b4 the same. With Aircoookie releases no problem.

**Comment by atuline** [comment]
Indeed. Sorry, we've had enough challenges which is why we disabled these other protocols by default.
