### ISSUE TITLE
sound sync: use of garbage from uninitialized memory

### ISSUE THREAD

**Issue by softhack007** [atuline/WLED#177]
Hi,
I've spotted a few lines of of code that might not work as intended.

1. either `packetHeader[]` is intentionally used as the source but without initialisation, meaning that some random data from the stack is copied into `receivedPacket`
2. or the intention was to copy parts from `receivedPacket` into `packetHeader[]`, but the order of arguments for memcpy is not correct.

The definition of `memcpy()` is 
```C++
void * memcpy ( void * destination, const void * source, size_t num );
```

Here
https://github.com/atuline/WLED/blob/575853db3af7ef4402b3f129c1a6012a23a7ed4e/wled00/usermod.cpp#L113-L120

**Comment by atuline** [comment]
I'll pass that along to @spedione who wrote the sound sync functionality.

In the meantime, would love to get your fixes incorporated into our repo. I'll try and have a look at yours over the weekend as time permits. If you're up for a PR at some point, it sure would be appreciated.

**Comment by softhack007** [comment]
Guess this is actually a bug - It seems that the parameters of `memcpy` are used in wrong order (swapping source and destination). Unfortunately I don't have a setup for using sound sync, so I cannot test what happens. Also I don't know what is expected to happen.

@chrishultin, @THATDONFC, @atuline  - I saw that you have also contributed to the code. Any ideas?

**Comment by chrishultin** [comment]
Definitely looks like I got the parameters mixed up for memcpy.  I think we need to swap the source and destination parameters to fix it.

**Comment by softhack007** [comment]
Fix in https://github.com/atuline/WLED/tree/dev_fix_audiosync
