### ISSUE TITLE
Seven Segment Display Reloaded Usermod 

### ISSUE THREAD

**Issue by al3x1337** [atuline/WLED#188]
**Is your feature request related to a problem? Please describe.**
Seven Segment Display Reloaded from Aircoookie/WLED:master is missing from SR
https://github.com/Aircoookie/WLED/tree/master/usermods/seven_segment_display_reloaded

**Describe the solution you'd like**
Seven Segment Display Reloaded added to this repo

**Describe alternatives you've considered**
I've tried to compile from scratch when I noticed the usermod is missing from this repo. I've added the usermod folder and made identical changes in const.h and usermods_list.cpp to those in the main WLED repo but get the follow error when compiling:

```wled00/../usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h:394:27: error: 'stateUpdated' was not declared in this scope
             stateUpdated(1);
                           ^
wled00/../usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h: In member function 'virtual void UsermodSSDR::onMqttConnect(bool)':
wled00/../usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h:463:75: warning: format '%S' expects argument of type 'wchar_t*', but argument 4 has type 'const char*' [-Wformat=]
       sprintf_P(subBuffer, PSTR("%s/%S/+/set"), mqttDeviceTopic, _str_name);
                                                                           ^
wled00/../usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h:463:75: warning: format '%S' expects argument of type 'wchar_t*', but argument 4 has type 'const char*' [-Wformat=]
wled00/../usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h:470:74: warning: format '%S' expects argument of type 'wchar_t*', but argument 4 has type 'const char*' [-Wformat=]
       sprintf_P(subBuffer, PSTR("%s/%S/+/set"), mqttGroupTopic, _str_name);
                                                                          ^
wled00/../usermods/seven_segment_display_reloaded/usermod_seven_segment_reloaded.h:470:74: warning: format '%S' expects argument of type 'wchar_t*', but argument 4 has type 'const char*' [-Wformat=]
*** [.pio\build\esp32dev\src\usermods_list.cpp.o] Error 1```


Can someone do a PR to add this or help point me in the right direction of what else I need to do to get this to compile? Thanks!

**Comment by al3x1337** [comment]
Just discovered the 13.1 branch that as the updated usermods
https://github.com/atuline/WLED/tree/dev-v0.13.1-merge

**Comment by al3x1337** [comment]
There's a bug within that branch:
![image](https://user-images.githubusercontent.com/44815197/160323270-75146e4c-ffbc-42dc-8852-aa186a709006.png)
The color wheel is missing and I can only use the CCT slider with RGB leds

**Comment by atuline** [comment]
Yep. Merging with AC's upstream master can often be challenging. We're looking into seeing what's wrong there.
