### ISSUE TITLE
No PC Mode in Chrome Browser

### ISSUE THREAD

**Issue by Coolie1101** [atuline/WLED#191]
**Describe the bug**
No "PC Mode" option in Chrome Browser.
![image](https://user-images.githubusercontent.com/28989417/161586261-08297020-b794-46e7-9e52-d10f5f8b78b2.png)

**To Reproduce**
Open WLED URL in Chrome Bowser

**Expected behavior**
Use Pc Mode in Chrome Browser, works in Edge or IE browsers.

**WLED version**
 - Board: - ESP32 dev
 - Version - 0.13.0-b6 (build 2112080)
 - ![image](https://user-images.githubusercontent.com/28989417/161587511-a5e0ef98-2299-4c98-abcd-94e7d26eb30e.png)
 - Format - Binary

**Additional context**
Sound Reactive Version

Thank you for your help!

**Comment by softhack007** [comment]
Could be a problem in upstream WLED, i,.e. not specific to our soundreactive fork?
