### ISSUE TITLE
WS2815 flickering at version 0.13.0-bx

### ISSUE THREAD

**Issue by razzz7** [atuline/WLED#199]
### What happened?

Since updating on version 0.13.x my WS2815 LEDs are flickering.
Downgrading back to version 0.12.0 and everything works fine.

I am using a quinled dig-quad / ESP32 

### To Reproduce Bug

update on version 0.13.0-b3 and higher

### Expected Behavior

No flickering

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.0-bx

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atuline** [comment]
Have you compared that to the exact same version of the original WLED?

**Comment by razzz7** [comment]
Just installed Aircoookie version 0.13.1 and have no issues.
Back to sound reactive 0.13.b leds flickering.

**Comment by atuline** [comment]
OTA updates maybe problematic because we've changed the file system. I'd do a fresh install:

https://github.com/atuline/WLED/wiki/Installing-and-Compiling#flashing-esp32-binaries

**Comment by razzz7** [comment]
Thx for the hint. I did a fresh install according to this guide, but issue still appeared. Turns out I had to reduce the automatic brightness limiter a bit.

**Comment by atuline** [comment]
If it's not one damn thing it's another. I've written pages of several things that can go wrong and that's just for FastLED animations. WLED takes it to a whole new stratosphere.

**Comment by razzz7** [comment]
Sry that I have to bring this issue up again.
I could narrow down the flickering.
After boot up/restart the leds are flickering. When I go to the led settings page and just hit save, without any changes, the flickering disappear and effects are normal.
