### ISSUE TITLE
Sync permanently activated

### ISSUE THREAD

**Issue by hektiker** [atuline/WLED#207]
Hey
Is it possible to set somewhere that the sync button is activated directly when WLED is started?

Useful if you use several ESPs in the network and switch off the power when not in use.

Maybe someone can help me there.

Best regards
Cedric

**Comment by netmindz** [comment]
Sounds like useful feature request, but not one that relates specifically to the Sound Reactive fork, so might be best to request upstream

**Comment by blazoncek** [comment]
You can add `"udpn":{"send":true}` to your boot preset.
