### ISSUE TITLE
Global brightness change does not trigger autosave usermod

### ISSUE THREAD

**Issue by primus192** [atuline/WLED#218]
### What happened?

When using autosave usermod changing global brightness bar or input level does not trigger autosave procedure

### To Reproduce Bug

Compile code with autosave enabled, change global brightness or sound input level, wait 15 seconds, the mod does not save

### Expected Behavior

For me expected behavior is that changing global brightness and input level should trigger autosave feature too.

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.13.2-a0 (build 2207140)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Solved for WLED SR in PR #219.

"Global Brightness" is a generic feature from WLED.
Please also report/create an issue in upstream WLED, to report that changing global brightness sliders does not trigger autosave mod. This will ensure that AC WLED devopers are aware of the problem.
