### ISSUE TITLE
mic type

### ISSUE THREAD

**Issue by TysTies** [atuline/WLED#232]
What microphone do you recommend?

**Comment by softhack007** [comment]
IMNP441 works well, other I2S digital mics are also possible.
https://github.com/atuline/WLED/wiki/Digital-Microphone-Hookup

Please join our discord to get community help and assistance with setting up WLED SR.

<a href="https://discord.gg/4CQRmfR"><img src="https://discordapp.com/api/guilds/700041398778331156/widget.png?style=banner2" width="25%"></a>

**Comment by TysTies** [comment]
thankyou
