### ISSUE TITLE
Looking for I2S ADC with line-In (Is PCM5102A possible?)

### ISSUE THREAD

**Issue by DenisMtfl** [atuline/WLED#234]
Hailege PCM5102 Module Stereo DAC Digital-to-Analog Converter PLL Voice Module For pHAT Format Digital Audio Board PCM5102 I2S IIS

**Comment by softhack007** [comment]
5102 is a DAC (digital to analog converter); output for connecting headphones or speakers. You are probably looking for an I2S ADC board with Line-In.

See my answer to your same question in discord.
https://discord.com/channels/700041398778331156/969595893584134164/1025025153953976390

**Comment by softhack007** [comment]
Question answered.
