### ISSUE TITLE
Random  effect presets does not work 

### ISSUE THREAD

**Issue by dosipod** [atuline/WLED#250]
### What happened?

Random  effect in a presets  or playlist  will not work :
e.g {"seg":{"fx":"r"}}  in a playlist will crash SRWLED13.3 and could result in issue with presets 

Also non-existing effect number 169 as pointed by @softhack007  will loop the gui ( MCU was accessible after power cycle )

### To Reproduce Bug

Use {"seg":{"fx":"r"}}   in a preset and call that preset with a play list .
you may also try  {"seg":{"fx":169}}  but this **may** brick the MCU ( It did not in our tests ) 

### Expected Behavior

{"seg":{"fx":"r"}}  will produce random effect without errors 

### Install Method

From https://wled-install.github.io/

### What version of Soundreactive WLED?

WLED 0.13.3 (build 2210301)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
We have tested WLED 0.13.3.3 (build 2211111) and {"seg":{"fx":"r"}}  still does not work

**Comment by softhack007** [comment]
Bug fixed, please try again with SR Build  2211172 or later.

**Comment by dosipod** [comment]
Issue seems to be resolved . We tested with 0.13.3.3 (build 2211183) , {"seg":{"fx":"r"}} in a playlists works as expected

**Comment by softhack007** [comment]
Fix included in latest v0.13.4-beta release
* https://github.com/atuline/WLED/releases/tag/v0.13.4-beta
