### ISSUE TITLE
FFT data for sound-reactive custom effects

### ISSUE THREAD

**Issue by protyposis** [atuline/WLED#259]
I would like to be able to write sound-reactive custom effects based on frequency magnitudes. It would be great if the FFT data, e.g., `fftResult`, was made available to the custom effect scripting language.

**Comment by netmindz** [comment]
That's already there, see GEQ for an example

**Comment by protyposis** [comment]
What is "GEQ"? I checked the [wiki](https://github.com/atuline/WLED/wiki/WLED-Custom-effects), [custom effects repo](https://github.com/MoonModules/WLED-Effects/tree/master/CustomEffects/wled), and [script interpreter source](https://github.com/atuline/WLED/blob/744dc734f4a70f479b7f93f1757dd4086392cf41/wled00/src/dependencies/arti/arti_wled.h), but wasn't able to identify this functionality.

**Comment by softhack007** [comment]
GEQ = graphical equalizer - one of the 2D effects in fx.cpp.
I think that @protyposis means to say that the same data (fftResult[]) cannot be used in the custom effect scripting language.

**Comment by protyposis** [comment]
Exactly! I updated my earlier comments for clarity.

**Comment by ewoudwijma** [comment]
It's done, see here: https://discord.com/channels/700041398778331156/905206400349765642/1053293141286998080

🥳

**Comment by protyposis** [comment]
I'm not registered there but have seen the video - this is great, thank you! 🚀 Can't wait to use it :)

**Comment by ewoudwijma** [comment]
It's now in WLED SR 0.13.3.6 and WLED MM 0.14.0.11.

If you download the new wledv033.json and presets.json and fftBrightness.wled after you press the Custom Effects button in Segments you can reproduce the effect.

Please try it out and if you create a new fft based effect, please share so we can add that to the library

**Comment by softhack007** [comment]
Included in latest v0.13.4-beta release
* https://github.com/atuline/WLED/releases/tag/v0.13.4-beta
