### ISSUE TITLE
gap file support

### ISSUE THREAD

**Issue by kenai2011** [atuline/WLED#272]
usually need for special led-setups it would be great to have this feature.
Is it planned to implement?

Thanks
kenai2011

**Comment by softhack007** [comment]
Hi, a similar feature is implemented in upstream WLED, called "gap maps".
This repo is in "maintenance mode" (bugfixing and stability improvements only), and we don't plan to add new features.

You could try the MoonModules fork which includes latest developments, based on latest WLED 0.14.0 source code.
* https://github.com/MoonModules/WLED/releases

**Comment by kenai2011** [comment]
Hi Frank,

 

thank you, i will check it asap.

 

BR

Kenai

 
 

Gesendet: Mittwoch, 06. September 2023 um 13:24 Uhr
Von: "Frank" ***@***.***>
An: "atuline/WLED" ***@***.***>
Cc: "kenai2011" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [atuline/WLED] gap file support (Issue #272)


 

Hi, a similar feature is implemented in upstream WLED, called "gap maps".
This repo is in "maintenance mode" (bugfixing and stability improvements only), and we don't plan to add new features.

You could try the MoonModules fork which includes latest developments, based on latest WLED 0.14.0 source code.


	https://github.com/MoonModules/WLED/releases
