### ISSUE TITLE
WiFi initialization "hangs"

### ISSUE THREAD

**Issue by GrumpyMeow** [atuline/WLED#41]
Hi Andrew,

I'm sometimes switching between my own Fork and your Fork. I noticed that after doing that, sometimes WiFi doesn't connect. It also doesn't initialize it's own Access Point.

I've done some debugging and have managed to get some information. This is the code-trail:
wled::loop 	-> handleConnection
wled::handleConnection -> initConnection
wled::initConnection	-> WiFi.config(0U, 0U, 0U);
(WiFiSTA.cpp)WiFiSTAClass::config
(WiFiGeneric.cpp) bool WiFiGenericClass::mode(wifi_mode_t m)

Eventually the following statement gets called (with m=1,_persistent=false): 
```err = esp_wifi_set_mode(m);```
For some reason this statement never returns. However if i change to:
```err = esp_wifi_set_mode(WIFI_MODE_APSTA);```
the statement does exit.

I'll update this issue. When i've found a solution or root-cause.

**Comment by softhack007** [comment]
closing - stale problem report, with only minimal information on how the problem can be reproduced.
Please join our Discord to get help and support from the SR WLED community.
https://discord.gg/4CQRmfR
