### ISSUE TITLE
What's the protocol for audio? Windows / Python App? as source?

### ISSUE THREAD

**Issue by zombodotcom** [atuline/WLED#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by THATDONFC** [comment]
Please update your original post to include the information necessary for us to help you.

**Comment by atuline** [comment]
I'm going to assume he's talking about the UDP sound sync, which is documented at:

https://github.com/atuline/WLED/wiki/UDP-Sound-Sync
