### ISSUE TITLE
Moin, mqtt is not saving. is that normaly.

### ISSUE THREAD

**Issue by scarefirego** [atuline/WLED#54]
**Describe the bug**
Moin, mqtt is not saving. is that normaly.

**WLED version**
 - Wemos D1, ESP32
 - Version 0.11.0
 - Format Binary

Thank you for your help!

**Comment by THATDONFC** [comment]
We have not made any changes to MQTT in our fork. Please submit an issue in the main WLED repo if you are having trouble with MQTT.

**Comment by jappyjan** [comment]
same for me. with original wled binary this does work...

**Comment by freizeitbastler** [comment]
have to confirm. SR WLED is not saving the mqtt information, the "normal" version is.
