### ISSUE TITLE
INMP441 how conect to D1Mini?

### ISSUE THREAD

**Issue by salopette** [atuline/WLED#61]
Hello, thanks for the WLED Mod!
I have an INMP441 microphone, which pins do I have to connect to the D1 Mini?

The micro has 6 (l / r, WS, SCK, GND, VDD and SD)
Thanks for your help!

**Comment by atuline** [comment]
If it's an ESP8266, you don't. If it's an ESP32, you may need to re-define the pins. Check the Discord for what others have done.

**Comment by salopette** [comment]
I have a Wemos D1 Mini. https://www.wemos.cc/en/latest/d1/d1_mini.html
So doesn't it work with that?

**Comment by atuline** [comment]
That page clearly says it's an ESP8266 (and I have about 30 WeMOS D1 Mini's), so no it doesn't support the INMP441. And the reason is that ESP32 supports I2S, while ESP8266 doesn't.

**Comment by salopette** [comment]
Thanks, now I understand it!
Is there any other microphone that is supported by esp8266 with the bin file?
I don't want to swap my 10 D1 for esp32 now.

**Comment by atuline** [comment]
https://github.com/atuline/WLED/wiki/Analog-Audio-Input-Options

**Comment by salopette** [comment]
Thanks a lot!
