### ISSUE TITLE
audioReactive _ ir romote

### ISSUE THREAD

**Issue by biseyleryapalim** [atuline/WLED#69]
audioReactive 0.10.1 ı have but ir remote control cant work normal wled0.10.1 can work but audioreactive cant work.
esp 8266-12f gıpo4 ir sencor  means d2 pin ?

**Comment by atuline** [comment]
Infra Red is disabled by default with SR WLED. See:

https://github.com/atuline/WLED/blob/0963544b074f322e18d61ea333f954e0f98b0f61/wled00/wled.h#L31

You'll need to re-enable and re-compile/upload. Sorry, but I don't understand the last line.
