### ISSUE TITLE
Apply sound preset at boot

### ISSUE THREAD

**Issue by ewoudwijma** [atuline/WLED#70]
Hi Atuline,
If I use a sound effect preset to be started at boot it sometime works and sometimes doesn't.
Is it possible that the Mike isn't initialized at boot procedure (in parallel thread?).
I have an inmp441 Mike and lolin32 board

**Comment by atuline** [comment]
Not sure what you mean by 'parallel thread'. Also, no mention of which branch or when you downloaded it.

In the dev and master branches (only), I have increased the delay time for startup of 100mS after the drivers are installed to
100mS upon power up and 250mS after the drivers are installed. This was added on March 4th.

**Comment by ewoudwijma** [comment]
Forget about parallel thread 😉 (I meant CPU threads, which is not standard supported on arduino, so probably no lt used in WLED).
I am not compiling directly now, i used the bin of feb 4, so running behind the latest version. I hope to find some time in the future to compile latest masters/devs myself.

**Comment by ewoudwijma** [comment]
Hi Atuline, I compiled the bin myself using VSC and everything is working like a charm! ![image](https://user-images.githubusercontent.com/1737159/111828832-2cc99580-88ec-11eb-9979-9096eb92e25b.jpeg)
