### ISSUE TITLE
How to use the new macro system?

### ISSUE THREAD

**Issue by JoshWobbles** [atuline/WLED#72]
I would like to have a button act as a momentary switch to a certain preset which will take over until the button is released and then return to previous program.

Use case is I use this on a motorcycle and would like to use your fork to add the sound reactive functionality, but I also like to wire in my brake light to turn all the leds red when braking.

**Comment by softhack007** [comment]
It seems that this question is not specific for the "sound reactive" fork of WLED. Did you already ask your question to upstream https://github.com/Aircoookie/WLED/issues?

**Comment by softhack007** [comment]
Closing this problem report, it seems to be 'stale'.

You may want to join the discord for getting community  support: https://discord.gg/4CQRmfR
