### ISSUE TITLE
2D led configuration not in 0.12.0

### ISSUE THREAD

**Issue by ewoudwijma** [atuline/WLED#76]
After installing the new 0.12.0 binary the 2D led width and height cannot be set in the led configuration settings anymore. As a consequence the 2D effects do not work anymore (all lights blinking red only).

Is it possible they got lost in merging with aircookie code?

**Comment by bigu1975** [comment]
confirmed gone for me as well

**Comment by madmic1314** [comment]
Confirmed as well. Did an upgrade so previous config are still there. But no settings option. Will be an issue with new configs

**Comment by merkisoft** [comment]
i tracked down the commit to this one where it got lost: https://github.com/atuline/WLED/commit/4f367b54010d6b53e60677f496127d6c9e16d01f

try multipin or revert like i did :)

**Comment by simon-hall** [comment]
Is this an 'easy' fix for a noob like me?  Or is it better to be patient and wait for the next release?  I'm eager to try out the 2D effects :)

If it's easy, can someone add a bit more detail to explain what to do?

**Comment by atuline** [comment]
IIRC, we're just waiting for the guy that worked on the 2D parameters to
integrate his fixes into a release.

In the meantime, the previous version should work just fine.

**Comment by madmic1314** [comment]
> Is this an 'easy' fix for a noob like me? Or is it better to be patient and wait for the next release? I'm eager to try out the 2D effects :)
> 
> If it's easy, can someone add a bit more detail to explain what to do?

Try this: flash the old version, erase the settings and then config as you need. Do an OTA upgrade. The settings are missing in the GUI but still working. Worked for me. I needed the newer version for the MIC bug fix that stopped boot.

**Comment by atuline** [comment]
No easy fix. You could, however try compiling our dev or even master branches. I'm not sure what their status is right now.

**Comment by simon-hall** [comment]
Thanks for the tips - flashing old version and upgrading worked for me.

**Comment by ewoudwijma** [comment]
I just played around for a while so just a beginner as well. Recently I managed to compile it myself using MS Code / PlatformIO. I compiled the dev of 20210419 which has the settings in it again. Shared the bin below which you can also install using OTA upgrade. @atuline, is this ok to share intermediate builds like this? Or is there another way in github to deal with intermediate builds?
[ws0.12.0dev20210419.bin.zip](https://github.com/atuline/WLED/files/6398113/ws0.12.0dev20210419.bin.zip)

**Comment by atuline** [comment]
Go ahead and share away. THATDONFC who (among other things) makes the builds/releases gets pretty busy at times, while my focus has always been on the FastLED stuff and how to make it work with volume/FFT input.
