### ISSUE TITLE
NO IR-Pin 

### ISSUE THREAD

**Issue by gitpower2017** [atuline/WLED#80]
Hello.

I cannot configure the IR pin.
It is always set to -1.
I use GIT V0.12 (Sound Reactive)
I have set the following in "platformio.ini" or "platformio_override.in"
I have set the IR function to PIN 4.

 - Board: LEDBoxV2 (esp32)
 - Version: 0.12.0
 - Format: self-compiled

Thank you for your help!

**Comment by mase76** [comment]
I have the same issue.

**Comment by biseyleryapalim** [comment]
Me too

12 Nis 2021 Pzt 23:02 tarihinde mase76 ***@***.***> şunu
yazdı:

**Comment by Leon751** [comment]
Is works with infrared. You must uncomment in the Code
//#define WLED-Disable-Infrared 
at wled.h and then compile.
In Wled sync Interfaces select the infrared remote and aktivate "send notification on button press or ir". 
At last in LED preferences set "IR pin" 4.

Good luck

**Comment by gitpower2017** [comment]
After adapting wled.h I can select PIN4 and the remote control (44 buttons) but the IR remote control does not work.
With the latest version of original wled source code, the remote control works.

**Comment by dirk0034** [comment]
how do compile??? has somebody a bin-file???

**Comment by mase76** [comment]
Here you are.
[esp32dev.zip](https://github.com/atuline/WLED/files/6540802/esp32dev.zip)

**Comment by dirk0034** [comment]
thx, but do you have this for 8266?

**Comment by mase76** [comment]
Just install VSCodium and PlatformIO. It is really simple. But you have to use the 8266 branch.

**Comment by atuline** [comment]
There's also the releases page:

https://github.com/atuline/WLED/releases

**Comment by mase76** [comment]
You enabled IR in these builds?

**Comment by dirk0034** [comment]
yes, in the 0.12, but after saving it shows -1

**Comment by mase76** [comment]
I meant, if atuline enabled the IR pin in the releases?

**Comment by dirk0034** [comment]
Oh, I don't know. And by myself I can't compile.
I every time flash the wemos with the bin

**Comment by dirk0034** [comment]
Hello again, ist there a .bin Version with IR for wemos d1 mini???

**Comment by atuline** [comment]
Have a chat with folks on the Discord channel. Maybe someone has enabled it and compiled it for that.
