### ISSUE TITLE
ESP32 not enough memory?

### ISSUE THREAD

**Issue by Leon751** [atuline/WLED#81]
Hello,
can it be that the ESP32 has too little memory when Alexa or infrared is activated?
I get the error "too little memory" when I activate Alexa or infrared in the Sketch.

**Comment by Leon751** [comment]
I have solved the problem. In the arduino ide was the memory setting default. Storage space was too low in the setting.

**Comment by atuline** [comment]
You managed to compile with the Arduino IDE? Good job. I gave up trying to do so several months ago. Your issue would've been a real challenge to find. Congrats on sorting that out.

**Comment by Leon751** [comment]
Yes i compile with Arduino IDE 1.8.13. I looked some Videos how to do this. It isnt so difficult. Installed esp32 board and library
Only the memory settings i didnt now.
i use partition scheme  No OTA (2MB APP/ 2MB SPIFFS)
and it worked
