### ISSUE TITLE
WS8215 strip

### ISSUE THREAD

**Issue by TheDarthFather** [atuline/WLED#88]
Hello,
Is WS8215 supported (seems so from the hardware setup) ? 
If so, as there is a backup data line .. do I need to connect D4 to both data and backup data lines ? 
I dont see a diagram for it on my strip as I had on the 8212B ...

PS: I returned a WS8212B wich was working, but it seems the data does not go to the 8215 as the strip does not react to the changes. The only difference is that now the ESP is connected to the USB port ... might be this or a cable issue.

**Comment by atuline** [comment]
Feel free to join the WLED Discord server for hardware discussion/support.
