### ISSUE TITLE
watefall

### ISSUE THREAD

**Issue by davidd1205** [atuline/WLED#89]
Hello thank you for your work
I use the latest compiled version to have alexa
I have a microphone on a ribbon and another ribbon without a microphone I transmit the sound of the first ribbon to the second everything works correctly except the waterfall which lights up just white on my second ribbon and works on that of the microphone

besides, is it useful to transfer the sound to another led tape or to just make a sync it comes back to the same of course if we use the same program I think it is useful to transmit the sound if the presets are different thank you anyway I also have to dig what is effect with the colors I sometimes do not understand I do not have a lot of color I have to leave default for the colors and applied the effects that's it thank you

esp 32 and immp441 for first strip and esp32 for a second strip

**Comment by atuline** [comment]
The sound information is transmitted completely independently of the effects. As a result, you can have Waterfall on the transmitting device and another animation on the receiver. You would still need to configure the palettes and the effects on the receiving device.

If you think there's a bug, we'll need a lot more information, preferably in point form. For BOTH devices we'd need things like version you're using, effect in use, values of sliders, selected palette, as well as sound settings on both devices.

 We would need to be able to re-create the environment and determine if it's actually a bug or that it's a configuration issue.
