### ISSUE TITLE
Unable to save Blynk Auth code under Sync Interface section.

### ISSUE THREAD

**Issue by amitav2002** [atuline/WLED#90]
**Describe the bug**
Firstly I would like to say big Thanks! to the dev team, who have developed this awasom Sound Reactive WLED project.

Dear Team, I am facing issue with Blynk Auth code, what I am not able to save. After save it, when I check, auth code shows clear. while it should be look like ****. This issue is only in Sound Reactive WLED, if I am using only WLED then it looks fine and working with Blynk App.

Other with ESP 8266 nodemcu, unable to save LED Data Pin.

**WLED version**
 - Board: ESP32 dev and ESP8266
 - Version : Sound Reactive WLED Version 0.12.0 - Runtime Configurable Pins!!!
 - Format : Download Bin file, Only I flashed it with ESP flasher.

Thank you for your help!

**Comment by atuline** [comment]
In wled.h, we've disabled most other functionality by default, such as Alexa, Blynk, Cronixie and so on.  You would need to modify the source and compile/upload. Either way, we're only supporting the web interface, so you would need to engage the WLED community on Discord for Blynk.
