### ISSUE TITLE
Help with UDP data

### ISSUE THREAD

**Issue by simon-hall** [atuline/WLED#91]
Hi

I'm trying to use the UDP data emitted by WLED using https://github.com/atuline/WLED/wiki/UDP-Sound-Sync as a guide.  

Am I correct in thinking that "fftResult" is 16 bytes representing the level of each frequency band? So if it's quiet, all bytes will be zero?  If I'm playing something with heavy bass I'd expect to see the value increasing in the first 8 or so bytes.  Treble would be in bytes 8-16 etc?

Or have I got the wrong end of the proverbial stick?

**Comment by simon-hall** [comment]
...and also I notice if I inspect the packets using TCP Dump, they're 88 bytes in length.  On the Wiki page the number of bytes adds up to 83.. where do the extra 5 bytes come from?

**Comment by atuline** [comment]
The Wiki probably needs to be updated from an older version of the UDP sound sync. In the meantime, you're right with the fftResult, and you'll probably want to look into audo_reactive.h for the gory details. As I recall, we used 16 bit for interim calculations, but ended up squeezing down the final results to 8 bits.
