### ISSUE TITLE
Button and Macros

### ISSUE THREAD

**Issue by duder56** [atuline/WLED#99]
So in the settings it says the macros have moved, and I can somewhat see where I'm supposed to edit the API under presets, but I am still unfamiliar with how to go about this, haha. Previously I used a macro someone had where it would use a button press to cycle through effects

FX=~

But I cannot seem to implement this into the API, moreover I would be more interested in making the button press cycle through my custom presets. 

If anyone could help it would be greatly appreciated.

**Comment by softhack007** [comment]
To ask support questions, please join the WLED audio Discord.

https://discord.gg/4CQRmfR
